<?php

namespace Database\Seeders;

use App\Models\Template;
use Illuminate\Database\Seeder;

class TemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            [
                'name' => 'NEONSPLASH',
                'slug' => 'neonsplash',
                'font_family' => 'Archivo Black',
                'primary_color' => '#CCFF00',
                'secondary_color' => '#FFFFFF',
                'background_color' => '#101010',
                'animation_type' => 'neonsplash',
                'sort_order' => 1,
                'config_json' => [
                    'badge' => 'New',
                    'category' => 'Bold & Shadow',
                    'tags' => ['SPLASH', 'CENTER'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 96,
                    'google_fonts' => 'Archivo+Black:wght@400',
                    'ffmpeg_font' => 'ArchivoBlack-Regular.ttf',
                ],
            ],
            [
                'name' => 'DUAL TONE SCRIPT',
                'slug' => 'dual-tone-script',
                'font_family' => 'Dancing Script',
                'primary_color' => '#C77DFF',
                'secondary_color' => '#FF6FD8',
                'background_color' => '#111827',
                'animation_type' => 'script-serif-combo',
                'sort_order' => 2,
                'config_json' => [
                    'badge' => 'New',
                    'category' => 'Elegant',
                    'tags' => ['GRADIENT', 'SCRIPT'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 90,
                    'google_fonts' => 'Dancing+Script:wght@700',
                    'ffmpeg_font' => 'DancingScript-Bold.ttf',
                ],
            ],
            [
                'name' => 'YELLOW SHADOW',
                'slug' => 'yellow-shadow',
                'font_family' => 'Poppins',
                'primary_color' => '#FFD60A',
                'secondary_color' => '#000000',
                'background_color' => '#0f172a',
                'animation_type' => 'bounce-baseline',
                'sort_order' => 3,
                'config_json' => [
                    'badge' => 'New',
                    'category' => 'Bold & Shadow',
                    'tags' => ['SHADOW', 'BOLD'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 96,
                    'google_fonts' => 'Poppins:wght@900',
                    'ffmpeg_font' => 'Poppins-Bold.ttf',
                ],
            ],
            [
                'name' => 'GOLDEN AURA',
                'slug' => 'golden-aura',
                'font_family' => 'Cinzel Decorative',
                'primary_color' => '#FFD700',
                'secondary_color' => '#B8860B',
                'background_color' => '#1a0010',
                'animation_type' => 'center-glow-focus',
                'sort_order' => 4,
                'config_json' => [
                    'badge' => 'New',
                    'category' => 'Elegant',
                    'tags' => ['GOLD', 'GRADIENT', 'GLOW'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 96,
                    'google_fonts' => 'Cinzel+Decorative:wght@700',
                    'ffmpeg_font' => 'CinzelDecorative-Regular.ttf',
                ],
            ],
            [
                'name' => 'GLASS BLUR',
                'slug' => 'glass-blur',
                'font_family' => 'Poppins',
                'primary_color' => '#FFFFFF',
                'secondary_color' => '#B8C0CC',
                'background_color' => '#090d16',
                'animation_type' => 'liquid-glass',
                'sort_order' => 5,
                'config_json' => [
                    'category' => 'Minimal',
                    'tags' => ['FROSTED', 'MINIMAL'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 84,
                    'google_fonts' => 'Poppins:wght@700',
                    'ffmpeg_font' => 'Poppins-Bold.ttf',
                ],
            ],
            [
                'name' => 'RETRO VHS',
                'slug' => 'retro-vhs',
                'font_family' => 'Rajdhani',
                'primary_color' => '#00F5FF',
                'secondary_color' => '#FF00FF',
                'background_color' => '#0a0a0f',
                'animation_type' => 'neon-glow',
                'sort_order' => 6,
                'config_json' => [
                    'category' => 'Textured/Grunge',
                    'tags' => ['RETRO', 'GLITCH'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 96,
                    'google_fonts' => 'Rajdhani:wght@700',
                    'ffmpeg_font' => 'Rajdhani-Bold.ttf',
                ],
            ],
            [
                'name' => 'COMIC POP',
                'slug' => 'comic-pop',
                'font_family' => 'Bebas Neue',
                'primary_color' => '#FFD166',
                'secondary_color' => '#EF476F',
                'background_color' => '#18181b',
                'animation_type' => 'comic-stroke',
                'sort_order' => 7,
                'config_json' => [
                    'category' => 'Playful',
                    'tags' => ['BOLD', 'PLAYFUL'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 110,
                    'google_fonts' => 'Bebas+Neue',
                    'ffmpeg_font' => 'BebasNeue-Regular.ttf',
                ],
            ],
            [
                'name' => 'MINIMAL MONO',
                'slug' => 'minimal-mono',
                'font_family' => 'Courier Prime',
                'primary_color' => '#FFFFFF',
                'secondary_color' => '#888888',
                'background_color' => '#0a0a0a',
                'animation_type' => 'typewriter-reveal',
                'sort_order' => 8,
                'config_json' => [
                    'category' => 'Minimal',
                    'tags' => ['CLEAN', 'MODERN'],
                    'duration' => 8,
                    'text_position' => 'center',
                    'font_size_large' => 64,
                    'google_fonts' => 'Courier+Prime:wght@700',
                    'ffmpeg_font' => 'CourierPrime-Regular.ttf',
                ],
            ],
            [
                'name' => 'HIGHLIGHT MARKER',
                'slug' => 'highlight-marker',
                'font_family' => 'Poppins',
                'primary_color' => '#000000',
                'secondary_color' => '#FFE66D',
                'background_color' => '#12121c',
                'animation_type' => 'color-highlight-split',
                'sort_order' => 9,
                'config_json' => [
                    'badge' => 'Popular',
                    'category' => 'Emphasis/Sync',
                    'tags' => ['EMPHASIS', 'POPULAR'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 88,
                    'google_fonts' => 'Poppins:wght@900',
                    'ffmpeg_font' => 'Poppins-Bold.ttf',
                ],
            ],
            [
                'name' => 'KARAOKE BOUNCE',
                'slug' => 'karaoke-bounce',
                'font_family' => 'Poppins',
                'primary_color' => '#FFFFFF',
                'secondary_color' => '#A3E635',
                'background_color' => '#0d0d16',
                'animation_type' => 'speech-flow',
                'sort_order' => 10,
                'config_json' => [
                    'badge' => 'Popular',
                    'category' => 'Emphasis/Sync',
                    'tags' => ['SYNC', 'POPULAR'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 88,
                    'google_fonts' => 'Poppins:wght@900',
                    'ffmpeg_font' => 'Poppins-Bold.ttf',
                ],
            ],
            [
                'name' => 'GLITCH CYBER',
                'slug' => 'glitch-cyber',
                'font_family' => 'Rajdhani',
                'primary_color' => '#00F5FF',
                'secondary_color' => '#FF0055',
                'background_color' => '#030712',
                'animation_type' => 'neon-glow',
                'sort_order' => 11,
                'config_json' => [
                    'category' => 'Bold & Shadow',
                    'tags' => ['GLITCH', 'BOLD'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 96,
                    'google_fonts' => 'Rajdhani:wght@700',
                    'ffmpeg_font' => 'Rajdhani-Bold.ttf',
                ],
            ],
            [
                'name' => 'BUBBLE POP',
                'slug' => 'bubble-pop',
                'font_family' => 'Caveat',
                'primary_color' => '#FFADAD',
                'secondary_color' => '#CAFFBF',
                'background_color' => '#1a0515',
                'animation_type' => 'heart-accent',
                'sort_order' => 12,
                'config_json' => [
                    'category' => 'Playful',
                    'tags' => ['PLAYFUL', 'ROUNDED'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 84,
                    'google_fonts' => 'Caveat:wght@700',
                    'ffmpeg_font' => 'Caveat-Regular.ttf',
                ],
            ],
            [
                'name' => 'INK SPLATTER',
                'slug' => 'ink-splatter',
                'font_family' => 'Fraunces',
                'primary_color' => '#E63946',
                'secondary_color' => '#FFFFFF',
                'background_color' => '#0a0505',
                'animation_type' => 'all-caps-bold-display',
                'sort_order' => 13,
                'config_json' => [
                    'category' => 'Textured/Grunge',
                    'tags' => ['GRUNGE', 'TEXTURED'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 100,
                    'google_fonts' => 'Fraunces:wght@900',
                    'ffmpeg_font' => 'Fraunces-Black.ttf',
                ],
            ],
            [
                'name' => 'CHROME METALLIC',
                'slug' => 'chrome-metallic',
                'font_family' => 'Oswald',
                'primary_color' => '#E2E8F0',
                'secondary_color' => '#94A3B8',
                'background_color' => '#0f172a',
                'animation_type' => 'rotate-in-transition',
                'sort_order' => 14,
                'config_json' => [
                    'category' => 'Bold & Shadow',
                    'tags' => ['PREMIUM', '3D'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 110,
                    'google_fonts' => 'Oswald:wght@700',
                    'ffmpeg_font' => 'Oswald-Bold.ttf',
                ],
            ],
            [
                'name' => 'Y2K SPARKLE',
                'slug' => 'y2k-sparkle',
                'font_family' => 'Dancing Script',
                'primary_color' => '#FF007F',
                'secondary_color' => '#E0E0E0',
                'background_color' => '#1a0015',
                'animation_type' => 'script-serif-combo',
                'sort_order' => 15,
                'config_json' => [
                    'category' => 'Playful',
                    'tags' => ['TRENDY', 'GLOW'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 90,
                    'google_fonts' => 'Dancing+Script:wght@700',
                    'ffmpeg_font' => 'DancingScript-Bold.ttf',
                ],
            ],
            [
                'name' => 'ELEGANT GOLD SERIF',
                'slug' => 'elegant-gold-serif',
                'font_family' => 'Playfair Display',
                'primary_color' => '#F5E6D3',
                'secondary_color' => '#D4AF37',
                'background_color' => '#1a0a00',
                'animation_type' => 'fade-reveal',
                'sort_order' => 16,
                'config_json' => [
                    'category' => 'Elegant',
                    'tags' => ['LUXURY', 'SERIF'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 84,
                    'google_fonts' => 'Playfair+Display:wght@700',
                    'ffmpeg_font' => 'PlayfairDisplay-Regular.ttf',
                ],
            ],
            [
                'name' => 'CONFETTI BURST',
                'slug' => 'confetti-burst',
                'font_family' => 'Archivo Black',
                'primary_color' => '#FFCC00',
                'secondary_color' => '#00FFCC',
                'background_color' => '#1e1b4b',
                'animation_type' => 'color-highlight-split',
                'sort_order' => 17,
                'config_json' => [
                    'category' => 'Playful',
                    'tags' => ['CELEBRATION', 'PLAYFUL'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 90,
                    'google_fonts' => 'Archivo+Black:wght@400',
                    'ffmpeg_font' => 'ArchivoBlack-Regular.ttf',
                ],
            ],
            [
                'name' => 'HANDWRITTEN NOTE',
                'slug' => 'handwritten-note',
                'font_family' => 'Caveat',
                'primary_color' => '#1D4ED8',
                'secondary_color' => '#475569',
                'background_color' => '#F8FAFC',
                'animation_type' => 'heart-accent',
                'sort_order' => 18,
                'config_json' => [
                    'category' => 'Personal',
                    'tags' => ['PERSONAL', 'CASUAL'],
                    'duration' => 6,
                    'text_position' => 'center',
                    'font_size_large' => 84,
                    'google_fonts' => 'Caveat:wght@700',
                    'ffmpeg_font' => 'Caveat-Regular.ttf',
                ],
            ],
        ];

        $validSlugs = array_column($templates, 'slug');
        Template::whereNotIn('slug', $validSlugs)->delete();

        foreach ($templates as $data) {
            Template::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
